

#if defined(STM8S207) || defined(STM8S208)


#define TLI_IRQHandler() 			            void TLI_IRQHandler()                       __interrupt(0)
#define AWU_IRQHandler() 			            void AWU_IRQHandler()                       __interrupt(1)
#define CLK_IRQHandler() 			            void CLK_IRQHandler()                       __interrupt(2)
#define EXTI_PORTA_IRQHandler() 	            void EXTI_PORTA_IRQHandler()                __interrupt(3)
#define EXTI_PORTB_IRQHandler() 	            void EXTI_PORTB_IRQHandler()                __interrupt(4)
#define EXTI_PORTC_IRQHandler() 	            void EXTI_PORTC_IRQHandler()                __interrupt(5)
#define EXTI_PORTD_IRQHandler() 	            void EXTI_PORTD_IRQHandler()                __interrupt(6)
#define EXTI_PORTE_IRQHandler() 	            void EXTI_PORTE_IRQHandler() 	            __interrupt(7)
#define CAN_RX_IRQHandler() 		            void CAN_RX_IRQHandler()		            __interrupt(8)
#define CAN_TX_IRQHandler() 		            void CAN_TX_IRQHandler() 		            __interrupt(9)
#define SPI_IRQHandler() 			            void SPI_IRQHandler() 			            __interrupt(10)
#define TIM1_UPD_OVF_TRG_BRK_IRQHandler()       void TIM1_UPD_OVF_TRG_BRK_IRQHandler()      __interrupt(11)
#define TIM1_CAP_COM_IRQHandler() 	            void TIM1_CAP_COM_IRQHandler()	            __interrupt(12)
#define TIM2_UPD_OVF_IRQHandler() 	            void TIM2_UPD_OVF_IRQHandler() 	            __interrupt(13)
#define TIM2_CAP_COM_IRQHandler()               void TIM2_CAP_COM_IRQHandler() 	            __interrupt(14)
#define TIM3_UPD_OVF_IRQHandler()               void TIM3_UPD_OVF_IRQHandler()	            __interrupt(15)
#define TIM3_CAP_COM_IRQHandler()               void TIM3_CAP_COM_IRQHandler()              __interrupt(16)
#define UART1_TX_IRQHandler()                   void UART1_TX_IRQHandler() 		            __interrupt(17)
#define UART1_RX_IRQHandler()                   void UART1_RX_IRQHandler() 		            __interrupt(18)
#define I2C_IRQHandler()                        void I2C_IRQHandler() 			            __interrupt(19)
#define UART3_TX_IRQHandler()                   void UART3_TX_IRQHandler() 		            __interrupt(20)
#define UART3_RX_IRQHandler()                   void UART3_RX_IRQHandler() 		            __interrupt(21)
#define ADC2_IRQHandler()                       void ADC2_IRQHandler() 			            __interrupt(22)
#define TIM4_UPD_OVF_IRQHandler()               void TIM4_UPD_OVF_IRQHandler()	            __interrupt(23)
#define FLASH_IRQHandler()                      void FLASH_IRQHandler() 		            __interrupt(24)

#endif


#if defined(STM8S007)

#define TLI_IRQHandler()                        void TLI_IRQHandler()                       __interrupt(0)
#define AWU_IRQHandler()                        void AWU_IRQHandler()                       __interrupt(1)
#define CLK_IRQHandler()                        void CLK_IRQHandler()                       __interrupt(2)
#define EXTI_PORTA_IRQHandler()                 void EXTI_PORTA_IRQHandler()                __interrupt(3)
#define EXTI_PORTB_IRQHandler()                 void EXTI_PORTB_IRQHandler()                __interrupt(4)
#define EXTI_PORTC_IRQHandler()                 void EXTI_PORTC_IRQHandler()                __interrupt(5)
#define EXTI_PORTD_IRQHandler()                 void EXTI_PORTD_IRQHandler()                __interrupt(6)
#define EXTI_PORTE_IRQHandler()                 void EXTI_PORTE_IRQHandler()                __interrupt(7)
#define SPI_IRQHandler()                        void SPI_IRQHandler()                       __interrupt(10)
#define TIM1_UPD_OVF_TRG_BRK_IRQHandler()       void TIM1_UPD_OVF_TRG_BRK_IRQHandler()      __interrupt(11)
#define TIM1_CAP_COM_IRQHandler()               void TIM1_CAP_COM_IRQHandler()              __interrupt(12)
#define TIM2_UPD_OVF_IRQHandler()               void TIM2_UPD_OVF_IRQHandler()              __interrupt(13)
#define TIM2_CAP_COM_IRQHandler()               void TIM2_CAP_COM_IRQHandler()              __interrupt(14)
#define TIM3_UPD_OVF_IRQHandler()               void TIM3_UPD_OVF_IRQHandler()              __interrupt(15)
#define TIM3_CAP_COM_IRQHandler()               void TIM3_CAP_COM_IRQHandler()              __interrupt(16)
#define UART1_TX_IRQHandler()                   void UART1_TX_IRQHandler()                  __interrupt(17)
#define UART1_RX_IRQHandler()                   void UART1_RX_IRQHandler()                  __interrupt(18)
#define I2C_IRQHandler()                        void I2C_IRQHandler()                       __interrupt(19)
#define UART3_TX_IRQHandler()                   void UART3_TX_IRQHandler()                  __interrupt(20)
#define UART3_RX_IRQHandler()                   void UART3_RX_IRQHandler()                  __interrupt(21)
#define ADC2_IRQHandler()                       void ADC2_IRQHandler()                      __interrupt(22)
#define TIM4_UPD_OVF_IRQHandler()               void TIM4_UPD_OVF_IRQHandler()              __interrupt(23)
#define FLASH_IRQHandler()                      void FLASH_IRQHandler()                     __interrupt(24)

#endif


#if defined(STM8S105) || defined(STM8S005)

#define TLI_IRQHandler()                        void TLI_IRQHandler()                       __interrupt(0)
#define AWU_IRQHandler()                        void AWU_IRQHandler()                       __interrupt(1)
#define CLK_IRQHandler()                        void CLK_IRQHandler()                       __interrupt(2)
#define EXTI_PORTA_IRQHandler()                 void EXTI_PORTA_IRQHandler()                __interrupt(3)
#define EXTI_PORTB_IRQHandler()                 void EXTI_PORTB_IRQHandler()                __interrupt(4)
#define EXTI_PORTC_IRQHandler()                 void EXTI_PORTC_IRQHandler()                __interrupt(5)
#define EXTI_PORTD_IRQHandler()                 void EXTI_PORTD_IRQHandler()                __interrupt(6)
#define EXTI_PORTE_IRQHandler()                 void EXTI_PORTE_IRQHandler()                __interrupt(7)
#define SPI_IRQHandler()                        void SPI_IRQHandler()                       __interrupt(10)
#define TIM1_UPD_OVF_TRG_BRK_IRQHandler()       void TIM1_UPD_OVF_TRG_BRK_IRQHandler()      __interrupt(11)
#define TIM1_CAP_COM_IRQHandler()               void TIM1_CAP_COM_IRQHandler()              __interrupt(12)
#define TIM2_UPD_OVF_IRQHandler()               void TIM2_UPD_OVF_IRQHandler()              __interrupt(13)
#define TIM2_CAP_COM_IRQHandler()               void TIM2_CAP_COM_IRQHandler()              __interrupt(14)
#define TIM3_UPD_OVF_IRQHandler()               void TIM3_UPD_OVF_IRQHandler()              __interrupt(15)
#define TIM3_CAP_COM_IRQHandler()               void TIM3_CAP_COM_IRQHandler()              __interrupt(16)
#define I2C_IRQHandler()                        void I2C_IRQHandler()                       __interrupt(19)
#define UART2_TX_IRQHandler()                   void UART2_TX_IRQHandler()                  __interrupt(20)
#define UART2_RX_IRQHandler()                   void UART2_RX_IRQHandler()                  __interrupt(21)
#define ADC1_IRQHandler()                       void ADC1_IRQHandler()                      __interrupt(22)
#define TIM4_UPD_OVF_IRQHandler()               void TIM4_UPD_OVF_IRQHandler()              __interrupt(23)
#define FLASH_IRQHandler()                      void FLASH_IRQHandler()                     __interrupt(24)

#endif


#if defined(STM8S103) || defined(STM8S003)

#define TLI_IRQHandler()                        void TLI_IRQHandler()                       __interrupt(0)
#define AWU_IRQHandler()                        void AWU_IRQHandler()                       __interrupt(1)
#define CLK_IRQHandler()                        void CLK_IRQHandler()                       __interrupt(2)
#define EXTI_PORTA_IRQHandler()                 void EXTI_PORTA_IRQHandler()                __interrupt(3)
#define EXTI_PORTB_IRQHandler()                 void EXTI_PORTB_IRQHandler()                __interrupt(4)
#define EXTI_PORTC_IRQHandler()                 void EXTI_PORTC_IRQHandler()                __interrupt(5)
#define EXTI_PORTD_IRQHandler()                 void EXTI_PORTD_IRQHandler()                __interrupt(6)
#define EXTI_PORTE_IRQHandler()                 void EXTI_PORTE_IRQHandler()                __interrupt(7)
#define SPI_IRQHandler()                        void SPI_IRQHandler()                       __interrupt(10)
#define TIM1_UPD_OVF_TRG_BRK_IRQHandler()       void TIM1_UPD_OVF_TRG_BRK_IRQHandler()      __interrupt(11)
#define TIM1_CAP_COM_IRQHandler()               void TIM1_CAP_COM_IRQHandler()              __interrupt(12)
#define TIM2_UPD_OVF_IRQHandler()               void TIM2_UPD_OVF_IRQHandler()              __interrupt(13)
#define TIM2_CAP_COM_IRQHandler()               void TIM2_CAP_COM_IRQHandler()              __interrupt(14)
#define UART1_TX_IRQHandler()                   void UART1_TX_IRQHandler()                  __interrupt(17)
#define UART1_RX_IRQHandler()                   void UART1_RX_IRQHandler()                  __interrupt(18)
#define I2C_IRQHandler()                        void I2C_IRQHandler()                       __interrupt(19)
#define ADC1_IRQHandler()                       void ADC1_IRQHandler()                      __interrupt(22)
#define TIM4_UPD_OVF_IRQHandler()               void TIM4_UPD_OVF_IRQHandler()              __interrupt(23)
#define FLASH_IRQHandler()                      void FLASH_IRQHandler()                     __interrupt(24)

#endif


#if defined(STM8S903)

#define TLI_IRQHandler()                        void TLI_IRQHandler()                       __interrupt(0)
#define AWU_IRQHandler()                        void AWU_IRQHandler()                       __interrupt(1)
#define CLK_IRQHandler()                        void CLK_IRQHandler()                       __interrupt(2)
#define EXTI_PORTA_IRQHandler()                 void EXTI_PORTA_IRQHandler()                __interrupt(3)
#define EXTI_PORTB_IRQHandler()                 void EXTI_PORTB_IRQHandler()                __interrupt(4)
#define EXTI_PORTC_IRQHandler()                 void EXTI_PORTC_IRQHandler()                __interrupt(5)
#define EXTI_PORTD_IRQHandler()                 void EXTI_PORTD_IRQHandler()                __interrupt(6)
#define EXTI_PORTE_IRQHandler()                 void EXTI_PORTE_IRQHandler()                __interrupt(7)
#define EXTI_PORTF_IRQHandler()                 void EXTI_PORTF_IRQHandler()                __interrupt(8)
#define SPI_IRQHandler()                        void SPI_IRQHandler()                       __interrupt(10)
#define TIM1_UPD_OVF_TRG_BRK_IRQHandler()       void TIM1_UPD_OVF_TRG_BRK_IRQHandler()      __interrupt(11)
#define TIM1_CAP_COM_IRQHandler()               void TIM1_CAP_COM_IRQHandler()              __interrupt(12)
#define TIM5_UPD_OVF_TRG_IRQHandler()           void TIM5_UPD_OVF_TRG_IRQHandler()          __interrupt(13)
#define TIM5_CAP_COM_IRQHandler()               void TIM5_CAP_COM_IRQHandler()              __interrupt(14)
#define UART1_TX_IRQHandler()                   void UART1_TX_IRQHandler()                  __interrupt(17)
#define UART1_RX_IRQHandler()                   void UART1_RX_IRQHandler()                  __interrupt(18)
#define I2C_IRQHandler()                        void I2C_IRQHandler()                       __interrupt(19)
#define ADC2_IRQHandler()                       void ADC2_IRQHandler()                      __interrupt(22)
#define TIM6_UPD_OVF_IRQHandler()               void TIM6_UPD_OVF_IRQHandler()              __interrupt(23)
#define FLASH_IRQHandler()                      void FLASH_IRQHandler()                     __interrupt(24)

#endif


#if defined(STM8L10X)

#define FLASH_IRQHandler()                      void FLASH_IRQHandler()                     __interrupt(1)
#define AWU_IRQHandler()                        void AWU_IRQHandler()                       __interrupt(4)
#define EXTIB_IRQHandler()                      void EXTIB_IRQHandler()                     __interrupt(6)
#define EXTID_IRQHandler()                      void EXTID_IRQHandler()                     __interrupt(7)
#define EXTI0_IRQHandler()                      void EXTI0_IRQHandler()                     __interrupt(8)
#define EXTI1_IRQHandler()                      void EXTI1_IRQHandler()                     __interrupt(9)
#define EXTI2_IRQHandler()                      void EXTI2_IRQHandler()                     __interrupt(10)
#define EXTI3_IRQHandler()                      void EXTI3_IRQHandler()                     __interrupt(11)
#define EXTI4_IRQHandler()                      void EXTI4_IRQHandler()                     __interrupt(12)
#define EXTI5_IRQHandler()                      void EXTI5_IRQHandler()                     __interrupt(13)
#define EXTI6_IRQHandler()                      void EXTI6_IRQHandler()                     __interrupt(14)
#define EXTI7_IRQHandler()                      void EXTI7_IRQHandler()                     __interrupt(15)
#define COMP_IRQHandler()                       void COMP_IRQHandler()                      __interrupt(18)
#define TIM2_UPD_OVF_TRG_BRK_IRQHandler()       void TIM2_UPD_OVF_TRG_BRK_IRQHandler()      __interrupt(19)
#define TIM2_CAP_IRQHandler()                   void TIM2_CAP_IRQHandler()                  __interrupt(20)
#define TIM3_UPD_OVF_TRG_BRK_IRQHandler()       void TIM3_UPD_OVF_TRG_BRK_IRQHandler()      __interrupt(21)
#define TIM3_CAP_IRQHandler()                   void TIM3_CAP_IRQHandler()                  __interrupt(22)
#define TIM4_UPD_OVF_IRQHandler()               void TIM4_UPD_OVF_IRQHandler()              __interrupt(25)
#define SPI_IRQHandler()                        void SPI_IRQHandler()                       __interrupt(26)
#define USART_TX_IRQHandler()                   void USART_TX_IRQHandler()                  __interrupt(27)
#define USART_RX_IRQHandler()                   void USART_RX_IRQHandler()                  __interrupt(28)
#define I2C_IRQHandler()                        void I2C_IRQHandler()                       __interrupt(29)

#endif


#if defined(STM8L15X_LD)

#define FLASH_IRQHandler()                      void FLASH_IRQHandler()                     __interrupt(1)
#define DMA1_CHANNEL0_1_IRQHandler()            void DMA1_CHANNEL0_1_IRQHandler()           __interrupt(2)    
#define DMA1_CHANNEL2_3_IRQHandler()            void DMA1_CHANNEL2_3_IRQHandler()           __interrupt(3)
#define RTC_IRQHandler()                        void RTC_IRQHandler()                       __interrupt(4)
#define EXTIE_F_PVD_IRQHandler()                void EXTIE_F_PVD_IRQHandler()               __interrupt(5)
#define EXTIB_IRQHandler()                      void EXTIB_IRQHandler()                     __interrupt(6)
#define EXTID_IRQHandler()                      void EXTID_IRQHandler()                     __interrupt(7)
#define EXTI0_IRQHandler()                      void EXTI0_IRQHandler()                     __interrupt(8)
#define EXTI1_IRQHandler()                      void EXTI1_IRQHandler()                     __interrupt(9)
#define EXTI2_IRQHandler()                      void EXTI2_IRQHandler()                     __interrupt(10)
#define EXTI3_IRQHandler()                      void EXTI3_IRQHandler()                     __interrupt(11)
#define EXTI4_IRQHandler()                      void EXTI4_IRQHandler()                     __interrupt(12)
#define EXTI5_IRQHandler()                      void EXTI5_IRQHandler()                     __interrupt(13)
#define EXTI6_IRQHandler()                      void EXTI6_IRQHandler()                     __interrupt(14)
#define EXTI7_IRQHandler()                      void EXTI7_IRQHandler()                     __interrupt(15)
#define CLK_CSS_IRQHandler()                    void CLK_CSS_IRQHandler()                   __interrupt(17)
#define ADC1_COMP_IRQHandler()                  void ADC1_COMP_IRQHandler()                 __interrupt(18)
#define TIM2_UPD_OVF_TRG_BRK_IRQHandler()       void TIM2_UPD_OVF_TRG_BRK_IRQHandler()      __interrupt(19)
#define TIM2_CAP_COM_IRQHandler()               void TIM2_CAP_COM_IRQHandler()              __interrupt(20)
#define TIM3_UPD_OVF_TRG_BRK_IRQHandler()       void TIM3_UPD_OVF_TRG_BRK_IRQHandler()      __interrupt(21)
#define TIM3_CAP_COM_IRQHandler()               void TIM3_CAP_COM_IRQHandler()              __interrupt(22)
#define RI_IRQHandler()                         void RI_IRQHandler()                        __interrupt(23)
#define TIM4_UPD_OVF_TRG_IRQHandler()           void TIM4_UPD_OVF_TRG_IRQHandler()          __interrupt(25) 
#define SPI1_IRQHandler()                       void SPI1_IRQHandler()                      __interrupt(26)
#define USART1_TX_IRQHandler()                  void USART1_TX_IRQHandler()                 __interrupt(27)
#define USART1_RX_IRQHandler()                  void USART1_RX_IRQHandler()                 __interrupt(28)
#define I2C_IRQHandler()                        void I2C_IRQHandler()                       __interrupt(29)

#endif


#if defined(STM8L15X_MD) || defined(STM8L15X_MDP) || defined(STM8L15X_HD)

#define FLASH_IRQHandler()                      void FLASH_IRQHandler()                     __interrupt(1)
#define DMA1_CHANNEL0_1_IRQHandler()            void DMA1_CHANNEL0_1_IRQHandler()           __interrupt(2)    
#define DMA1_CHANNEL2_3_IRQHandler()            void DMA1_CHANNEL2_3_IRQHandler()           __interrupt(3)
#define RTC_IRQHandler()                        void RTC_IRQHandler()                       __interrupt(4)
#define EXTIE_F_PVD_IRQHandler()                void EXTIE_F_PVD_IRQHandler()               __interrupt(5)
#define EXTIB_G_IRQHandler()                    void EXTIB_G_IRQHandler()                   __interrupt(6)
#define EXTID_H_IRQHandler()                    void EXTID_H_IRQHandler()                   __interrupt(7)
#define EXTI0_IRQHandler()                      void EXTI0_IRQHandler()                     __interrupt(8)
#define EXTI1_IRQHandler()                      void EXTI1_IRQHandler()                     __interrupt(9)
#define EXTI2_IRQHandler()                      void EXTI2_IRQHandler()                     __interrupt(10)
#define EXTI3_IRQHandler()                      void EXTI3_IRQHandler()                     __interrupt(11)
#define EXTI4_IRQHandler()                      void EXTI4_IRQHandler()                     __interrupt(12)
#define EXTI5_IRQHandler()                      void EXTI5_IRQHandler()                     __interrupt(13)
#define EXTI6_IRQHandler()                      void EXTI6_IRQHandler()                     __interrupt(14)
#define EXTI7_IRQHandler()                      void EXTI7_IRQHandler()                     __interrupt(15)
#define LCD_IRQHandler()                        void LCD_IRQHandler()                       __interrupt(16)
#define CLK_TIM1_DAC_IRQHandler()               void CLK_TIM1_DAC_IRQHandler()              __interrupt(17)
#define ADC1_COMP_IRQHandler()                  void ADC1_COMP_IRQHandler()                 __interrupt(18)
#define TIM2_UPD_OVF_TRG_BRK_IRQHandler()       void TIM2_UPD_OVF_TRG_BRK_IRQHandler()      __interrupt(19)
#define TIM2_CAP_COM_IRQHandler()               void TIM2_CAP_COM_IRQHandler()              __interrupt(20)
#define TIM3_UPD_OVF_TRG_BRK_IRQHandler()       void TIM3_UPD_OVF_TRG_BRK_IRQHandler()      __interrupt(21)
#define TIM3_CAP_COM_IRQHandler()               void TIM3_CAP_COM_IRQHandler()              __interrupt(22)
#define TIM1_OVF_TRG_COM_IRQHandler()           void TIM1_OVF_TRG_COM_IRQHandler()          __interrupt(23)
#define TIM1_CAP_COM_IRQHandler()               void TIM1_CAP_COM_IRQHandler()              __interrupt(24)
#define TIM4_UPD_OVF_TRG_IRQHandler()           void TIM4_UPD_OVF_TRG_IRQHandler()          __interrupt(25) 
#define SPI1_IRQHandler()                       void SPI1_IRQHandler()                      __interrupt(26)
#define USART1_TX_IRQHandler()                  void USART1_TX_IRQHandler()                 __interrupt(27)
#define USART1_RX_IRQHandler()                  void USART1_RX_IRQHandler()                 __interrupt(28)
#define I2C_IRQHandler()                        void I2C_IRQHandler()                       __interrupt(29)

#endif


#if defined(STM8L05X_LD_VL)

#define FLASH_IRQHandler()                      void FLASH_IRQHandler()                     __interrupt(1)
#define DMA1_CHANNEL0_1_IRQHandler()            void DMA1_CHANNEL0_1_IRQHandler()           __interrupt(2)    
#define DMA1_CHANNEL2_3_IRQHandler()            void DMA1_CHANNEL2_3_IRQHandler()           __interrupt(3)
#define RTC_IRQHandler()                        void RTC_IRQHandler()                       __interrupt(4)
#define PVD_IRQHandler()                        void PVD_IRQHandler()                       __interrupt(5)
#define EXTIB_IRQHandler()                      void EXTIB_IRQHandler()                     __interrupt(6)
#define EXTID_IRQHandler()                      void EXTID_IRQHandler()                     __interrupt(7)
#define EXTI0_IRQHandler()                      void EXTI0_IRQHandler()                     __interrupt(8)
#define EXTI1_IRQHandler()                      void EXTI1_IRQHandler()                     __interrupt(9)
#define EXTI2_IRQHandler()                      void EXTI2_IRQHandler()                     __interrupt(10)
#define EXTI3_IRQHandler()                      void EXTI3_IRQHandler()                     __interrupt(11)
#define EXTI4_IRQHandler()                      void EXTI4_IRQHandler()                     __interrupt(12)
#define EXTI5_IRQHandler()                      void EXTI5_IRQHandler()                     __interrupt(13)
#define EXTI6_IRQHandler()                      void EXTI6_IRQHandler()                     __interrupt(14)
#define EXTI7_IRQHandler()                      void EXTI7_IRQHandler()                     __interrupt(15)
#define CLK_CSS_IRQHandler()                    void CLK_CSS_IRQHandler()                   __interrupt(17)
#define ADC1_COMP_IRQHandler()                  void ADC1_COMP_IRQHandler()                 __interrupt(18)
#define TIM2_UPD_OVF_TRG_BRK_IRQHandler()       void TIM2_UPD_OVF_TRG_BRK_IRQHandler()      __interrupt(19)
#define TIM2_CAP_COM_IRQHandler()               void TIM2_CAP_COM_IRQHandler()              __interrupt(20)
#define TIM3_UPD_OVF_TRG_BRK_IRQHandler()       void TIM3_UPD_OVF_TRG_BRK_IRQHandler()      __interrupt(21)
#define TIM3_CAP_COM_IRQHandler()               void TIM3_CAP_COM_IRQHandler()              __interrupt(22)
#define RI_IRQHandler()                         void RI_IRQHandler()                        __interrupt(23)
#define TIM4_UPD_OVF_TRG_IRQHandler()           void TIM4_UPD_OVF_TRG_IRQHandler()          __interrupt(25) 
#define SPI1_IRQHandler()                       void SPI1_IRQHandler()                      __interrupt(26)
#define USART1_TX_IRQHandler()                  void USART1_TX_IRQHandler()                 __interrupt(27)
#define USART1_RX_IRQHandler()                  void USART1_RX_IRQHandler()                 __interrupt(28)
#define I2C_IRQHandler()                        void I2C_IRQHandler()                       __interrupt(29)

#endif